name: Build and Test

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Package Source Distribution
      run: python setup.py sdist

    - name: Upload Source Distribution
      uses: actions/upload-artifact@v2
      with:
        name: sdist
        path: dist/
