name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pyspark==3.3.3
        pip install chispa==0.9.4

    - name: List contents of root directory
      run: ls -l

    - name: Run command
      run: |
        python client_data/dataset_one.csv client_data/dataset_two.csv "United Kingdom,Netherlands"

