name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pyspark==3.3.3
        pip install chispa==0.9.4

    - name: Package Source Distribution
      run: |
        cd ..
        python setup.py sdist

    - name: Upload Source Distribution
      uses: actions/upload-artifact@v2
      with:
        name: sdist
        path: dist/

    - name: Run Pyspark main class
      run: python main.py client_data\dataset_one.csv client_data\dataset_two.csv  "United Kingdom,Netherlands"
