name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pyspark==3.3.3
        pip install chispa==0.9.4

    - name: Package Source Distribution
      run: |
        python https://github.com/ArvindKarthik/kommatipara/blob/af3f22d5bbf120209f57175bf901e7d1cf4783e3/setup.py sdist

    - name: Upload Source Distribution
      uses: actions/upload-artifact@v2
      with:
        name: sdist
        path: dist/
